package co.parameta.technical.test.soap.util.mapper;

import co.parameta.technical.test.commons.pojo.TypeDocumentPojo;
import co.parameta.technical.test.commons.util.mapper.BaseMapper;
import com.parameta.technical.test.soap.gen.TypeDocument;
import org.mapstruct.Mapper;

/**
 * Mapper responsible for converting type document information between
 * SOAP-generated objects and internal POJOs.
 * <p>
 * This mapper handles the transformation between {@link TypeDocument}
 * elements defined in the SOAP contract and {@link TypeDocumentPojo}
 * objects used by the application logic.
 * </p>
 *
 * <p>
 * The implementation is generated by MapStruct and follows the
 * generic conversion rules defined in {@link BaseMapper}.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface TypeDocumentMapper extends BaseMapper<TypeDocument, TypeDocumentPojo> {

}
